name: Pack on windows-latest platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4.1.4
 
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "MinGW Makefiles"

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Deploy Compress folder
      run: |
        copy C:\mingw64\bin\libgcc_s_seh-1.dll ${{github.workspace}}\bin\Koro_Caster_Service\
        copy C:\mingw64\bin\libstdc++-6.dll ${{github.workspace}}\bin\Koro_Caster_Service\
        copy C:\mingw64\bin\libwinpthread-1.dll ${{github.workspace}}\bin\Koro_Caster_Service\
        tar -czvf windows-latest.tar.gz ${{github.workspace}}\bin\Koro_Caster_Service\

    - name: Upload Release
      uses: actions/upload-artifact@v4.3.3
      with:
        # 上传后文件的名称
        name: ububtu-latest
        # 上传的压缩包
        path: ububtu-latest.tar.gz
